sudo: true
language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

notifications:
  email: false

# Install stuff
before_install:
  - travis/install_sge.sh
  - export SGE_ROOT=/var/lib/gridengine
  - export SGE_CELL=default
  - export DRMAA_LIBRARY_PATH=/usr/lib/libdrmaa.so.1.0
install:
  - pip install python-coveralls --use-mirrors
  - pip install nose-cov --use-mirrors
  - python setup.py install

# Run test
script:
  - nosetests -d -v --with-cov --cov drmaa --cov-config .coveragerc --logging-level=DEBUG

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc

